add_definitions (-DUNICODE)

if (NOT CMAKE_BUILD_TYPE MATCHES Debug)
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Zi")
    set (CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} /DEBUG")
endif (NOT CMAKE_BUILD_TYPE MATCHES Debug)
