file (STRINGS VERSION VERSION_STRINGS LIMIT_COUNT 4)

list (GET VERSION_STRINGS 0 MAJOR_VERSION)
list (GET VERSION_STRINGS 1 MINOR_VERSION)
list (GET VERSION_STRINGS 2 FIX_VERSION)
list (GET VERSION_STRINGS 3 SPEC_VERSION)

if (${SPEC_VERSION} STREQUAL "")
    set (VERSION "${MAJOR_VERSION}.${MINOR_VERSION}.${FIX_VERSION}")
else ()
    set (VERSION "${MAJOR_VERSION}.${MINOR_VERSION}.${FIX_VERSION}.${SPEC_VERSION}")
endif ()
